[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "forculus"
authors = [{name = "Martin", email = "me@miluminatti.tk"}]
dynamic = ["version", "description"]